nari/cli/client.py, nari/io/actlog.py, nari/io/reader.py, nari/parser/__init__.py, nari/parser/normaliser.py, nari/parser/normalizer.py, nari/types/event/base.py, nari/types/event/directorupdate.py, nari/types/event/zonechange.py
A first normalization pass. In particular, this does a number of things:
* Focuses more on 'streams' of data by changing the Reader abstract base into an iterator under the hood – by overriding the `read_next` method, the class handles the rest of it being iterable. This enables some nice scenarios where iterating through pre-created lists of events or a reader is functionally the same code
* In keeping with this 'streams' design, there's now an abstract `Normaliser` class that takes a List of iterable of Events and processes them allowing you to do a normalization pass. **Note**: I have found that Act-based logs do not always write their events to a file in the correct order, so there may be a need for a `TimeOrder` normalizer or some such.
* I updated the cli frontend to provide a more …
=> Normalization first pass

nari/types/event/directorupdate.py, nari/types/event/networktargetheadmarker.py
I honestly have no idea why this uses the padding at the end of an IPC's GameEvent segment header, but it do.
=> Update NetworkTargetHeadMarker docs for known param details

nari/cli/client.py, nari/cli/fightlist.py, nari/parser/analyser.py
* Add an 'Analyser' class that allows you to hook the event stream and run certain higher-level parsing activities. This is separate from the concept of a Normaliser because Normalisers can also pass events through, and the purpose of Analysers is to process that data rather than normalize/transmit that data
* Rewrite the cli default representation to use an implementation of an analyser both to show a good example and because it reduces bloat in `client.py` anyway
=> Analyzer first pass

nari/io/writer/__init__.py
Really, this fix is needed to address a bug in naritai's db writer, but it adds an override-able 'cleanup' method that writers can use to perform any cleanup they need after the last item has been written (might not trigger in batch mode)
=> Allow writers to clean up their mess

setup.py
**Purpose**
Bump pylint ver
Fixes an issue with pylint
**Bug Fixes**
Fixes error output with pylint (see [here](https://github.com/PyCQA/pylint/issues/4184))
before
```
E0611: No name 'unpack' in module 'struct' (no-name-in-module)
```
no after error is gone
=> pin pylint version to 2.7.3

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/effectresult.py
**Purpose**
This is a first pass at adding networkeffectresult events and parsing to the actlogreader
The event and parsing
**Bug Fixes**
Probably lots of them which are unfixd
New event if you were to do the following:
```python
for event in reader: # reader is of type ActLogReader
print(event)
```
I'm sad.
=> Add networkeffectresult event(s) and actlog parsing

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/ability.py, nari/types/event/ability.py
**Purpose**
My purpose is to write code and resolve #41 
Adds sequence IDs
**Bug Fixes**
This does fix the bug of not parsing aoeabilitie events from the act log
I'm less sad, but still working on it.
=> Add sequence ids to ability events

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/cast.py, nari/types/event/startcast.py
**Purpose**
Parse more events, specifically:
* startcast
* stopcast
And while I was there, I fixed some incorrect parsing (duration in StartCast is a float, not an integer)
Parse 2 new events (listed above)
**Bug Fixes**
Fixes the bug of not having so many unparsed events
Before: no start/stop cast events
After: start/stop cast events
Don't let any surgeon tell you that any operation where they cut into your abdominal wall is an easy one – you use core muscles for more than you know until you suddenly have issues just sitting up.
=> Parse more events, get rid of some TODOs

nari/cli/client.py, nari/cli/fightlist.py, nari/io/reader/__init__.py, nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/ability.py, nari/io/reader/actlogutils/actorspawn.py, nari/io/reader/actlogutils/cast.py, nari/io/reader/actlogutils/death.py, nari/io/reader/actlogutils/directorupdate.py, nari/io/reader/actlogutils/effectresult.py, nari/io/reader/actlogutils/gauge.py, nari/io/reader/actlogutils/limitbreak.py, nari/io/reader/actlogutils/metadata.py, nari/io/reader/actlogutils/party.py, nari/io/reader/actlogutils/playerstats.py, nari/io/reader/actlogutils/status.py, nari/io/reader/actlogutils/updatehp.py, nari/io/reader/actlogutils/visibility.py, nari/io/reader/actlogutils/zone.py, nari/io/writer/__init__.py, nari/parser/analyser.py, nari/parser/normaliser.py, nari/types/actioneffect.py, nari/types/event/ability.py, nari/types/event/config.py, nari/types/event/effectresult.py, nari/types/event/party.py, nari/types/event/playerstats.py, nari/types/event/statuslist.py
**Purpose**
In my merciless march towards progress, I'm adding 3.10 type annotations, specifically targeting `typing.List` and `typing.Dict` (though I do get some `typing.Union` shortcuts). As a result, we have one less import in *many* files.
3.10 typing changes are reflected in the code
**Bug Fixes**
N/A
Huge diff in code, no change in output
Crocodiles can "gallop" at speeds up to 11mph (17.7 km/h)
=> Add python 3.10-style type annotations

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/cast.py
**Purpose**
This removes some TODOs from `nari.io.reader.actlogutils`'s `ID_MAPPINGS` dict as we don't currently have plans to parse them.
Since I'm removing TODOs, I removed the one in the begincast logline parser by actually parsing the position/facing data like the TODO asked for
Position data in `StartCast` event
**Bug Fixes**
Happier pylint, so happier me.
Before: No position data in `StartCast`
After: Position data in `StartCast`
You can figure out if any value is a number (regardless of if it's an int/float/complex number type) by using `numbers.Number`, since all numerical objects pseudo-inherit from it:
```python
>>> from numbers import Number
>>> isinstance(4, Number)
True
>>> isinstance(3.14159, Number)
True
>>> …
```
=> Removing TODOs

nari/io/reader/actlogutils/__init__.py
**Purpose**
Add (and ignore) event id 41
41 is now known. And now ignored.
**Bug Fixes**
Fixes #60 
Before: Exception raised with `raise_on_checksum_failure=True`
After: no exception
There are more than 9 different species of boa constrictors
=> Ignore act event id 41

nari/io/reader/actlog.py, nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/targeticon.py, nari/types/event/markers.py
Templates are for people that use generics - I threw in the enum for player markers but not waymarks, alongside an implementation of *only* the content markers. Not sure if syntax is gucci and we should prob have rules for import ordering at some point but yolo it is.
=> Target Icons

nari/io/reader/actlog.py, nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/ability.py, nari/io/reader/actlogutils/actorspawn.py, nari/io/reader/actlogutils/cast.py, nari/io/reader/actlogutils/death.py, nari/io/reader/actlogutils/directorupdate.py, nari/io/reader/actlogutils/effectresult.py, nari/io/reader/actlogutils/exceptions.py, nari/io/reader/actlogutils/gauge.py, nari/io/reader/actlogutils/limitbreak.py, nari/io/reader/actlogutils/metadata.py, nari/io/reader/actlogutils/party.py, nari/io/reader/actlogutils/playerstats.py, nari/io/reader/actlogutils/status.py, nari/io/reader/actlogutils/targeticon.py, nari/io/reader/actlogutils/targetmarker.py, nari/io/reader/actlogutils/tether.py, nari/io/reader/actlogutils/updatehp.py, nari/io/reader/actlogutils/visibility.py, nari/io/reader/actlogutils/waymark.py, nari/io/reader/actlogutils/zone.py
Events are now prefixed by memory/network depending on their source, as well as unused for events that are defined but not used. The internal events have been left alone. All missing events have been added, and a consistency pass was run over the major class docstrings. I'll do a few more passes of docs including the native nari events in a later PR.
=> Cleanup ACT event names and docstrings

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/status.py, nari/types/event/statuslist.py
This isn't really used much, since the other 3 statuslist packets all get turned into statuslist1 (and statuslist2 isn't used at all), but it's a thing so here we are. Might be worth just repurposing the statuslist event if we make classjob optional, I'll leave that to the reviewer.
=> Add parser for simplified StatusList loglines

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/tick.py, nari/types/event/ticks.py
Kinda preserving the differentiation of damage and heal events in the types. Since these are actor controls, I'm fairly sure the effect ID is just padding and not used since it's the usual "actor control param 2 isn't used" thing, but I can't find my notes anywhere. ACT indicates it's used for ground effects tho.
=> Add parser for Effects over Time

nari/io/reader/actlogutils/directorupdate.py
**Purpose**
We have python 3.10, so let's use more match statements
Just generally more readable (less readable since I'm using dictionary merging?) than a bunch of elifs
**Bug Fixes**
N/A
Probably best to check the diff since this shouldn't provide a functional difference
Please don't ask me to write tests for this.
=> switch to match statements

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/updatehpmp.py, test/actlog/test_act_utils.py, test/actlog/test_marker_parsing.py, test/actlog/test_updatehpmp_parsing.py
SP field is often empty and breaks things. This makes it not break things, and adds a test. Additionally resolves some deprecation warnings.
=> Fix UpdateHPMP

.vscode/settings.json
This just hides some build files/folders you don't need in the editor. I didn't set the python path to auto venv as we don't use venv here really, and the python plugin for vsc is pretty good at finding it automatically. PYC files are conditionally hidden if they're for an accompanying python source file, if they're leftover junk tho they'll show up so easy to find and delete.
=> Add vscode settings.json to avoid cluttering the file tree

pyproject.toml, setup.cfg, test/event/__init__.py, test/test_reader.py
**Purpose**
This adds code coverage reports
Code coverage, configured to maximum meanness - here's the output of the last result of `coverage run -m unittest && coverage report`:
```
Name                               Stmts   Miss Branch BrPart  Cover
--------------------------------------------------------------------
nari/__init__.py                       2      0      0      0   100%
nari/io/__init__.py                    0      0      0      0   100%
nari/io/reader/__init__.py            15      0      2      0   100%
nari/io/reader/pickle.py              14     14      0      0     0%
nari/io/writer/__init__.py            19     10      2      0    43%
nari/io/writer/pickle.py              12     12      0      0     0%
nari/types/__init__.py                 4      0 …
```
=> Code coverage reports

.github/workflows/test.yml
**Purpose**
This should enable codecov support, now that Ax got the github permissions sorted
Coverage support on PR to make us feel bad
**Bug Fixes**
N/A
Hopefully this will provide code coverage charts on future PRs
```awk
{print;}
```
is probably the worst awk one-liner.
=> Add codecov support

.github/workflows/test.yml, test/test_utils.py
Cleanup the workflow too to bring it back into sync with `nari-act`. It does seem a little odd that the coverage action needs to exec again tho.
Things not tested:
- exceptions, most of them probably don't need to exist in `nari` anymore
- non-padded `hexstr_to_int` since while I can hit the line for coverage, I can't think of a good way to validate it actually works as expected
- failure-case tests
I'm not sure why checks aren't showing for this PR, but it should double the coverage (only because 7x2 is 14 tho)
=> Add Tests for nari.util
