xivlogs/nari

.gitignore, nari/types/event/directorupdate.py
Clarifying some formatting and adding command type `0x4000000E`.
=> Additional DirectorUpdate docs

nari/cli/client.py, nari/io/reader.py, nari/parser/normaliser.py
Running mypy against the codebase has pointed out a few typing errors I had, but it also doesn't like the iterators returning generic `Event`s instead of their real types. Worth some further consideration long-term.
=> Typing fixes

.github/workflows/test.yml, setup.py
Please commit #6 first, otherwise this will start complaining about the existing code.
=> Add mypy to requisite checks so I can stop writing bad code

.pylintrc, nari/types/actor.py, nari/types/event/ability.py
* Modify the Ability code to parse more of the previously unparsed params
* Document what I can, though most of the effect data is unknown at this
time
* Add some helper classes to the Actor class to represent resources (hp,mp,tp) and position (xyz and facing)
* Modify pylintrc to accept short values of x, y, z, hp, mp, and tp
Big thanks to Furst and Wintermute for helping me get the data for a lot of this documentation
=> Networkability improvements

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/status.py, nari/parser/analyser.py, nari/types/actioneffect.py, nari/types/director.py, nari/types/event/actorspawn.py, nari/types/event/instance.py, nari/types/event/statuslist.py, nari/types/event/stopcast.py, nari/types/status.py
**Purpose**
More pylint fixes
Less pylint issues
**Bug Fixes**
No
Less pylint issues in ci output
More pylint fixes because it has a requirement of 10/10 pylint
=> more pylint fixes

.github/workflows/test.yml, test/actlog/test_helper_functions.py
**Purpose**
Add testing scaffolding for nari
This should set python's unittest as the testing framework and fixes #24 
**Bug Fixes**
N/A
No functional changes, except for github workflows
N/A
=> Clean up workflows; add test scaffolding

nari/io/reader/actlogutils/playerstats.py, nari/types/event/playerstats.py
**Purpose**
1: Player event parse was not correct
2: Breaks stats into attributes
None
**Bug Fixes**
Mentioned by Luna in the Discord
Waiting for tests to make sure it works
I am 100% sure this is ugly is sin and I'm hoping I'm on the right track and someone can provide some sort of feedback to make it look prettier
=> breaks stats into attrs and fixes line parse

nari/io/reader/actlog.py, nari/io/reader/pickle.py, nari/io/writer/pickle.py
**Purpose**
More fixes for pylint and closing file handles when the parent object goes through garbage collection
Less pylint bugs, less potential memory leaks.
=> Fix some pylint issues and clean up file handles where appropriate

nari/io/reader/actlog.py, nari/io/reader/pickle.py, nari/io/writer/pickle.py
**Purpose**
When @nonowazu submitted his last PR it was flagging on these values. New pylint is okay with them.
**Bug Fixes**
less pylint errors
=> remove msgs because new pylint doesnt like them

nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/party.py, nari/types/event/party.py
**Purpose**
You know what I'm here for. I'm here to make friends and implement PartyList.
...and I'm all out of Friends.
Adds PartyList event and helping parser for act
**Bug Fixes**
N/A
Before: No PartyList event
After: PartyList event
I listened to the Smash Mouth cover of *Why Can't We Be Friends* while I wrote this. Now I have no friends.
=> Add partylist event

nari/io/reader/actlog.py, nari/io/reader/actlogutils/party.py, nari/types/event/actorspawn.py, nari/types/event/playerstats.py
**Purpose**
Fix linting errors.
Less linting errors
**Bug Fixes**
Closer to a green checkmark on the lint pass
Before: 9.something on lint.
After: 9.99 on lint (at least on my machine)
I'd like to have friends.
=> Get pylint to 9.99

nari/io/reader/actlogutils/__init__.py
Fixes #62 
Yes yes, PR form filling, I'm not going to do it because I've filled out too many of these TPS reports tonight. The code is short and pretty self-explanatory.
I get grumpy when I'm close to sleep.
=> Add both bs target markers with the "acceptable" (sarcasm) names

nari/io/reader/actlog.py, nari/io/reader/actlogutils/__init__.py, nari/io/reader/pickle.py, nari/io/writer/pickle.py, setup.py
**Purpose**
Bump pylint to 2.13 and update overrides
While we expect new features to have some degree of prior discussion, bug fixes are fine to
submit as-is. If there is a discussion, we appreciate links here to simplify tracking it down.
Pylint will be 2.13
**Bug Fixes**
Pylint will not complain about being 2.13
No output changes
There is a vegetarian crocodile in Madagascar
=> Bump pylint to 2.13 and update overrides

README.md, setup.py
Updates the readme and setup.py. I'm not filling out the form for non-code changes, sorry.
**Additional Information**
Not filling out the form.
=> Update README and bump setup version

nari/io/reader/actlog.py, nari/io/reader/actlogutils/__init__.py, nari/io/reader/actlogutils/exceptions.py, nari/io/reader/actlogutils/targeticon.py, nari/io/reader/actlogutils/tether.py, nari/io/reader/actlogutils/tick.py, nari/io/reader/actlogutils/waymark.py, nari/types/event/version.py, test/actlog/test_act_utils.py
=> Fix validation for md5 and sha256, and some broken parsing

.pylintrc, nari/types/event/version.py, nari/util/exceptions.py, test/actlog/test_version.py
=> Fix broken version string parsing

nari/util/byte.py
~~**Purpose**~~
~~A clear and concise description of what the PR is aiming to achieve. Commit messages explain
what you did, and the diff shows us how, but a description on your goal provides context for
reviewers.~~
~~While we expect new features to have some degree of prior discussion, bug fixes are fine to
submit as-is. If there is a discussion, we appreciate links here to simplify tracking it down.~~
~~**New Features**~~
~~Have you discussed this in Discussions or an Issue? Please provide a link if so.~~
~~**Bug Fixes**~~
~~Has the bug been reported in an Issue? Please provide a link if so.~~
~~**Before/After**~~
~~If this PR changes output, please post a short comparison for review.~~
Ah, the real meat of this PR template (ignore the branch name).
This just …
=> Add option to flip bytes

.gitignore
**Purpose**
~~Why must programs be a pain.~~ Adds JetBrains to the ignore list.
~~Error detected trying to reboot.~~ N/A
**Bug Fixes**
~~Fault found in sector...~~ N/A
~~Irrecoverable error, shutting down.~~ N/A
~~Booting GLaD OS...~~
=> Add JetBrains IDE folders and files to the gitignore list.

nari/util/pair.py
**Purpose**
Rusty code things.
**Bug Fixes**
Yes.
Rust shenanigans
=> allow for integers to be passed to IdNamePair

setup.cfg
~~**Purpose**~~
~~A clear and concise description of what the PR is aiming to achieve. Commit messages explain
what you did, and the diff shows us how, but a description on your goal provides context for
reviewers.~~
~~While we expect new features to have some degree of prior discussion, bug fixes are fine to
submit as-is. If there is a discussion, we appreciate links here to simplify tracking it down.~~
~~**New Features**~~
~~Have you discussed this in Discussions or an Issue? Please provide a link if so.~~
~~**Bug Fixes**~~
~~Has the bug been reported in an Issue? Please provide a link if so.~~
~~**Before/After**~~
~~If this PR changes output, please post a short comparison for review.~~
~~**Additional Context**~~
~~Add any other context or notable details about the PR here.~~
[Big …
=> Tell setup.cfg to use package_data
